# Generated by Django 4.2.4 on 2023-08-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_scope_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
